In [1]:
import xgboost as xgb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import src.train_utils as T
import itertools
import random

In [2]:
df = pd.read_csv('../datasets/dataset_base.csv')
df['date'] = pd.to_datetime(df['date'])

train_df = df[df['date'].dt.year < 2022]

In [3]:
control_df = train_df[['row', 'col', 'date', 'delta_pm25_t', 'delta_pm25_t+1']]
control_df.head()

   row  col       date  delta_pm25_t  delta_pm25_t+1
0    0    0 2018-07-05      0.302968        0.601407
1    0    0 2018-07-06      0.601407        0.038002
2    0    0 2018-07-07      0.038002        0.556278
3    0    0 2018-07-08      0.556278       -0.491020
4    0    0 2018-07-09     -0.491020        1.041161

### Randomized Hyperparameter Search

In [ ]:
param_grid = {
    'max_depth': [4, 6, 8],
    'learning_rate': [0.05, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'n_estimators': [300, 500]
}

# 2. Generate all hyperparameter combinations
param_list = list(itertools.product(
    param_grid['max_depth'],
    param_grid['learning_rate'],
    param_grid['subsample'],
    param_grid['colsample_bytree'],
    param_grid['n_estimators']
))

# 3. Randomly sample a subset
n_samples = 20  # or however many trials you want
random.seed(191)  # reproducibility
sampled_params = random.sample(param_list, min(n_samples, len(param_list)))

# 3. Initialize tracking
results = []

# 4. For each hyperparameter setting
for params in sampled_params:
    max_depth, learning_rate, subsample, colsample_bytree, n_estimators = params

    model = xgb.XGBRegressor(
        objective='reg:squarederror',
        max_depth=max_depth,
        learning_rate=learning_rate,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        n_estimators=n_estimators,
        random_state=191
    )

    rmse_scores, mae_scores = T.rolling_window_cv(
        train_days=365 * 2,
        gap_days=21,
        test_days=60,
        df=control_df,
        model=model
    )

    mean_rmse = np.mean(rmse_scores)
    se_rmse = np.std(rmse_scores)

    mean_mae = np.mean(mae_scores)
    se_mae = np.std(mae_scores)

    print("Summary of Performance Statistics")
    print(f"RMSE: {mean_rmse} +/- {se_rmse}")
    print(f"MAE: {mean_mae} +/- {se_mae}")

    results.append((params, mean_rmse))

best_params, best_score = min(results, key=lambda x: x[1])
print("Best parameters:", best_params)
print("Best average RMSE:", best_score)

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6610864331215185
MAE: 1.0046119332320411
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.265336976457552
MAE: 2.177977929955929
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309499283029077
MAE: 5.279105736917975
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477285619805523
MAE: 9.305458266236561
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849226066736387
MAE: 2.6855442538824
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.052554341929309
MAE: 0.8185394821145112
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2843955604813735
MAE: 0.9224955986220128
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.100562504191294
MAE: 2.1979278910141784
Summary of Performance Statistics
RMSE: 4.749993348219004 +/- 3.8880509012001068
MAE: 3.0489576364969513 +/- 2.7250743691615433
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6610864331215185
MAE: 1.0046119332320411
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.265336976457552
MAE: 2.177977929955929
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309499283029077
MAE: 5.279105736917975
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477285619805523
MAE: 9.305458266236561
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849226066736387
MAE: 2.6855442538824
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.052554341929309
MAE: 0.8185394821145112
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2843955604813735
MAE: 0.9224955986220128
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.100562504191294
MAE: 2.1979278910141784
Summary of Performance Statistics
RMSE: 4.749993348219004 +/- 3.8880509012001068
MAE: 3.0489576364969513 +/- 2.7250743691615433
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.661185742117569
MAE: 1.004752023328399
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264882523217756
MAE: 2.177893018125215
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.30975963141368
MAE: 5.279190077246179
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477851694894506
MAE: 9.305753646280866
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849424720319575
MAE: 2.6856555813702014
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0524965569779725
MAE: 0.8184938869759746
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2843285798091633
MAE: 0.9224178492089844
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.100410392817294
MAE: 2.197761889700855
Summary of Performance Statistics
RMSE: 4.7500424801959396 +/- 3.8882368007184103
MAE: 3.048989746529584 +/- 2.725174897720504
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6618800286384399
MAE: 1.005489259503991
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.266169497196989
MAE: 2.1785489548891492
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309820007111245
MAE: 5.279436874579158
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477705123909956
MAE: 9.305653254241415
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849720801563047
MAE: 2.6861463864205386
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0536203743543218
MAE: 0.8194028647713991
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.284958672775417
MAE: 0.9229537395179003
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1007231281304906
MAE: 2.198108164927797
Summary of Performance Statistics
RMSE: 4.750574704209988 +/- 3.8879335873703726
MAE: 3.0494674373564186 +/- 2.7249090297379084
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6608790479631468
MAE: 1.0045632047437956
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264362787323237
MAE: 2.177423560437211
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309145973356997
MAE: 5.278711184027159
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.47693459207647
MAE: 9.305156073644321
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.84874163426322
MAE: 2.6851162869278324
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.052364904871975
MAE: 0.8183504835756414
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2840076910823286
MAE: 0.9222275354104852
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.10029052518486
MAE: 2.197597544175788
Summary of Performance Statistics
RMSE: 4.749590894515279 +/- 3.888006409548449
MAE: 3.048643234117779 +/- 2.7250395167593178
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6610083709882744
MAE: 1.0045319609235506
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264579301303433
MAE: 2.1777768342608486
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309456749834819
MAE: 5.279094380406168
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477119147656818
MAE: 9.305351146450018
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.848929123772617
MAE: 2.685376075654179
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0524586934399456
MAE: 0.8184231057021675
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2843149822737971
MAE: 0.9224051772636802
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1005251673033816
MAE: 2.197874178010958
Summary of Performance Statistics
RMSE: 4.749798942071636 +/- 3.8880172781372946
MAE: 3.048854107333946 +/- 2.7250836261235034
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6613222482385739
MAE: 1.0047953386328485
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264207482747111
MAE: 2.1780217823883055
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309889940333541
MAE: 5.279288828643845
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477943744806018
MAE: 9.305760565405713
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849583079594789
MAE: 2.6858763141159483
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.052753170899687
MAE: 0.8186761322113938
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2844010826042531
MAE: 0.9224705318045002
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1005053652773875
MAE: 2.197838894785914
Summary of Performance Statistics
RMSE: 4.75007576431267 +/- 3.8882055207705353
MAE: 3.0490910484985587 +/- 2.7251473100410277
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.661682988639249
MAE: 1.005253233003925
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.266100248932819
MAE: 2.178367343459004
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309756888766506
MAE: 5.27933751536241
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477659777047462
MAE: 9.305603003541673
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849636262631669
MAE: 2.6859945447114835
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.053344470642012
MAE: 0.8191707498393914
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2847581838170186
MAE: 0.9227779509632061
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1006561965369928
MAE: 2.1980209706421707
Summary of Performance Statistics
RMSE: 4.750449377126716 +/- 3.8879925032363936
MAE: 3.049315663940408 +/- 2.7249606603837067
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.660822389803622
MAE: 1.0046034575579663
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264709547015908
MAE: 2.1773070776533237
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309272177284879
MAE: 5.27865369968755
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.476999903915296
MAE: 9.305143064170236
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.8488415700461305
MAE: 2.685097539593844
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.052543454167145
MAE: 0.8184852973058185
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2841115852541025
MAE: 0.922435575408312
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.100177669105266
MAE: 2.197482643797832
Summary of Performance Statistics
RMSE: 4.7496847870740435 +/- 3.8880199912985383
MAE: 3.048651044396861 +/- 2.725001499055343
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.66116857333761
MAE: 1.0047043635361745
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.265948018678029
MAE: 2.1778714948859417
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309523309924887
MAE: 5.2790461432560996
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477487255649644
MAE: 9.305403882751605
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849341217038278
MAE: 2.6855242889665827
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0526767566125055
MAE: 0.8186288665910887
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2843380654579817
MAE: 0.9224548174598327
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1004669963439198
MAE: 2.197789701821732
Summary of Performance Statistics
RMSE: 4.750118774130357 +/- 3.8881087114626287
MAE: 3.048927944908632 +/- 2.725048811390291
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6617659247557437
MAE: 1.0053449080971348
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.266143982858012
MAE: 2.1784692762387983
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309798057642484
MAE: 5.2793898239829
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477688629290224
MAE: 9.305626899364755
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849673636558602
MAE: 2.6860652352549654
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.053455016427875
MAE: 0.8192639586916756
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2848343866855727
MAE: 0.9228465271758157
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.100682921864329
MAE: 2.198051253554505
Summary of Performance Statistics
RMSE: 4.7505053195103555 +/- 3.8879735463804552
MAE: 3.0493822352950684 +/- 2.7249416151560153
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6613222482385739
MAE: 1.0047953386328485
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264207482747111
MAE: 2.1780217823883055
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309889940333541
MAE: 5.279288828643845
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477943744806018
MAE: 9.305760565405713
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849583079594789
MAE: 2.6858763141159483
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.052753170899687
MAE: 0.8186761322113938
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2844010826042531
MAE: 0.9224705318045002
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1005053652773875
MAE: 2.197838894785914
Summary of Performance Statistics
RMSE: 4.75007576431267 +/- 3.8882055207705353
MAE: 3.0490910484985587 +/- 2.7251473100410277
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6611766531143337
MAE: 1.0046212156139418
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264622936646894
MAE: 2.177939632570593
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309381197000459
MAE: 5.279138377463074
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477233301042364
MAE: 9.305484089595144
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849086017293352
MAE: 2.6855341146341516
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.052892115284898
MAE: 0.8188099241070398
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.284498535228385
MAE: 0.9225317127284183
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1005881426326147
MAE: 2.197955149876401
Summary of Performance Statistics
RMSE: 4.749934862280412 +/- 3.8879522925190315
MAE: 3.0490017770735953 +/- 2.7250536935501257
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.661557130820614
MAE: 1.0050806325413115
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.266055639914402
MAE: 2.178267182815101
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309734161144056
MAE: 5.279297013453984
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.47764033455922
MAE: 9.305572883988585
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849561174628624
MAE: 2.6858636274786343
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.053248020441128
MAE: 0.8190993088794397
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2846269159268213
MAE: 0.9226692149187812
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1005854938124737
MAE: 2.197945150141527
Summary of Performance Statistics
RMSE: 4.750376108905917 +/- 3.8880265380406773
MAE: 3.0492243767771705 +/- 2.7249911174185195
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6610083709882744
MAE: 1.0045319609235506
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264579301303433
MAE: 2.1777768342608486
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309456749834819
MAE: 5.279094380406168
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477119147656818
MAE: 9.305351146450018
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.848929123772617
MAE: 2.685376075654179
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0524586934399456
MAE: 0.8184231057021675
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2843149822737971
MAE: 0.9224051772636802
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.1005251673033816
MAE: 2.197874178010958
Summary of Performance Statistics
RMSE: 4.749798942071636 +/- 3.8880172781372946
MAE: 3.048854107333946 +/- 2.7250836261235034
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.661185742117569
MAE: 1.004752023328399
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.264882523217756
MAE: 2.177893018125215
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.30975963141368
MAE: 5.279190077246179
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477851694894506
MAE: 9.305753646280866
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849424720319575
MAE: 2.6856555813702014
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0524965569779725
MAE: 0.8184938869759746
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2843285798091633
MAE: 0.9224178492089844
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.100410392817294
MAE: 2.197761889700855
Summary of Performance Statistics
RMSE: 4.7500424801959396 +/- 3.8882368007184103
MAE: 3.048989746529584 +/- 2.725174897720504
Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6617659247557437
MAE: 1.0053449080971348
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.266143982858012
MAE: 2.1784692762387983
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.309798057642484
MAE: 5.2793898239829
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.477688629290224
MAE: 9.305626899364755
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.849673636558602
MAE: 2.6860652352549654
Fold 6

Best Params: (4, 0.1, 0.8, 0.8, 500)

In [6]:
params = {'max_depth': 4, 'learning_rate': 0.1, 'subsample': 0.8, 'colsample_bytree': 0.8, 'n_estimators': 500}

In [47]:
exp_1_df

,row,col,date,pm25_t,u_wind_10m,v_wind_10m,dew_temp_2m,temp_2m,surf_pressure,precip_sum,...,delta_pm25_t_r1_c-2,delta_pm25_t_r1_c-1,delta_pm25_t_r1_c0,delta_pm25_t_r1_c1,delta_pm25_t_r1_c2,delta_pm25_t_r2_c-2,delta_pm25_t_r2_c-1,delta_pm25_t_r2_c0,delta_pm25_t_r2_c1,delta_pm25_t_r2_c2
112320,2,2,2018-07-05,8.506299,1.099417,0.845259,292.53455,297.36017,88500.480,1.085705e-03,...,0.506664,0.420908,1.175132,1.152598,0.412996,0.275500,-0.419762,0.973524,0.522349,0.302968
112321,2,2,2018-07-06,7.291668,0.536112,0.847002,292.94757,296.90536,88492.290,2.183610e-03,...,-0.233806,-0.559418,-1.652848,-1.761432,0.167479,-0.186723,-0.095932,-1.125940,-1.001619,0.601407
112322,2,2,2018-07-07,8.418976,0.653129,0.892963,293.46637,296.09024,88523.930,1.098063e-02,...,-0.039803,0.708406,1.128092,1.741480,0.411181,0.311488,0.669046,0.587489,1.064866,0.038002
112323,2,2,2018-07-08,9.029675,0.758944,0.372737,293.11792,295.39346,88557.590,7.403880e-03,...,0.436303,0.311186,0.570811,0.926645,1.613415,0.208978,0.167542,0.058055,0.060918,0.556278
112324,2,2,2018-07-09,9.116474,0.735163,0.694967,292.74075,295.87690,88641.150,1.645568e-03,...,0.123422,-0.060415,-0.185492,-0.514772,-1.492460,0.251034,0.176971,0.625493,0.339427,-0.491020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303803,41,41,2021-12-27,21.843426,-1.568173,-0.212587,287.75488,293.73010,95798.210,2.097818e-05,...,-9.537959,-12.137171,-8.159606,-6.374832,-6.324257,-9.670241,-14.552199,-10.942500,-5.915656,-5.896442
2303804,41,41,2021-12-28,18.682210,-1.002234,-0.391176,286.59882,293.61517,95750.990,4.410744e-07,...,-1.771536,-2.445273,-3.504840,-4.787384,-5.964996,-0.231837,0.978988,-0.261930,-5.346428,-5.612656
2303805,41,41,2021-12-29,21.692741,-1.128024,-0.570042,287.97546,294.03458,95779.375,4.266560e-06,...,2.188764,3.974985,3.253660,3.584790,2.722079,1.806360,2.974662,3.822099,4.014383,3.273466
2303806,41,41,2021-12-30,19.682276,-1.364955,-0.540719,287.61550,293.62190,95875.930,1.715147e-06,...,-3.071544,-3.512343,-1.171859,-2.556478,-1.015366,-3.052140,-2.895143,-2.726351,-2.949779,-1.906230
2303807,41,41,2021-12-31,21.002811,-1.121278,-0.633195,286.49695,293.27188,95851.960,8.523463e-07,...,2.822516,1.497075,0.162093,2.199004,0.915133,2.337177,1.679272,1.290856,1.651027,1.482515

In [84]:
exp_1_df = train_df.copy()

base_df = exp_1_df.copy()
shifts = []
for row_shift in [-2, -1, 0, 1, 2]:
    for col_shift in [-2, -1, 0, 1, 2]:
        if not (row_shift == 0 and col_shift == 0):  # skip center cell
            shifts.append((row_shift, col_shift))

for row_shift, col_shift in shifts:
    shifted = base_df.copy()
    shifted['row'] += row_shift
    shifted['col'] += col_shift

    # Naming convention
    col_name_pm = f'pm25_t_r{-row_shift}_c{-col_shift}'
    col_name_delta = f'delta_pm25_t_r{-row_shift}_c{-col_shift}'

    base_df = base_df.merge(
        shifted[['row', 'col', 'date', 'pm25_t', 'delta_pm25_t']].rename(columns={'pm25_t': col_name_pm, 'delta_pm25_t': col_name_delta}),
        on=['row', 'col', 'date'],
        how='left'
    )

exp_1_df = base_df.dropna()

In [87]:
exp_1_df.to_csv('exp_1_dataset.csv', index=False)

## Control 1: Current Pixel Only

In [91]:
control_df = exp_1_df[['row', 'col', 'date', 'delta_pm25_t', 'delta_pm25_t+1']]
control_df.head()

        row  col       date  delta_pm25_t  delta_pm25_t+1
112320    2    2 2018-07-05      0.774012       -1.214631
112321    2    2 2018-07-06     -1.214631        1.127308
112322    2    2 2018-07-07      1.127308        0.610699
112323    2    2 2018-07-08      0.610699        0.086799
112324    2    2 2018-07-09      0.086799        0.337736

In [92]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=control_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5897928502961691
MAE: 1.001991590397039
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.618287266480897
MAE: 2.227218569097601
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.36944173771286
MAE: 5.327215970615451
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.494239477873599
MAE: 9.335713399547238
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.673510526115822
MAE: 2.6647422491553363
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0643947649868184
MAE: 0.827335253199704
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2824402274431383
MAE: 0.9224717113617616
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.0619666420424134
MAE: 2.183681004250072
Summary of Performance Statistics
RMSE: 4.7692591866189655 +/- 3.913502710512307
MAE: 3.061296218453025 +/- 2.737054524098696

## + 4 Neighbors

In [93]:
four_neighbors_df = exp_1_df[['row', 'col', 'date', 'delta_pm25_t', 
                              'delta_pm25_t_r1_c0', 'delta_pm25_t_r-1_c0',
                              'delta_pm25_t_r0_c1', 'delta_pm25_t_r0_c-1',
                              'delta_pm25_t+1']]
four_neighbors_df.head()

,row,col,date,delta_pm25_t,delta_pm25_t_r1_c0,delta_pm25_t_r-1_c0,delta_pm25_t_r0_c1,delta_pm25_t_r0_c-1,delta_pm25_t+1
112320,2,2,2018-07-05,0.774012,0.198054,1.175132,0.815492,1.526387,-1.214631
112321,2,2,2018-07-06,-1.214631,-0.564943,-1.652848,-0.376699,-2.001883,1.127308
112322,2,2,2018-07-07,1.127308,1.057073,1.128092,0.389675,1.450109,0.610699
112323,2,2,2018-07-08,0.610699,0.560488,0.570811,0.433100,0.941031,0.086799
112324,2,2,2018-07-09,0.086799,-0.156699,-0.185492,0.020303,-0.670372,0.337736

In [94]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=four_neighbors_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5785777921831667
MAE: 1.0013792503747463
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.613008644961647
MAE: 2.229501816930823
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.3442446642488015
MAE: 5.312837267287146
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.529997485038093
MAE: 9.344804929425639
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.645750868302276
MAE: 2.6533022790397864
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0743554391322407
MAE: 0.8379624698442981
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2847795423092345
MAE: 0.9273106680343102
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.037391857966847
MAE: 2.1757775601106326
Summary of Performance Statistics
RMSE: 4.763513286767788 +/- 3.922399032691443
MAE: 3.0603595301309223 +/- 2.737123519183118

## + 3x3

In [96]:
three_df = exp_1_df[['row', 'col', 'date', 'delta_pm25_t', 
                    'delta_pm25_t_r1_c0', 'delta_pm25_t_r-1_c0',
                    'delta_pm25_t_r0_c1', 'delta_pm25_t_r0_c-1',
                    'delta_pm25_t_r1_c1', 'delta_pm25_t_r1_c-1',
                    'delta_pm25_t_r-1_c1', 'delta_pm25_t_r-1_c-1',
                    'delta_pm25_t+1']]

three_df.head()

,row,col,date,delta_pm25_t,delta_pm25_t_r1_c0,delta_pm25_t_r-1_c0,delta_pm25_t_r0_c1,delta_pm25_t_r0_c-1,delta_pm25_t_r1_c1,delta_pm25_t_r1_c-1,delta_pm25_t_r-1_c1,delta_pm25_t_r-1_c-1,delta_pm25_t+1
112320,2,2,2018-07-05,0.774012,0.198054,1.175132,0.815492,1.526387,0.119964,-0.102599,0.420908,1.152598,-1.214631
112321,2,2,2018-07-06,-1.214631,-0.564943,-1.652848,-0.376699,-2.001883,0.452158,-0.351426,-0.559418,-1.761432,1.127308
112322,2,2,2018-07-07,1.127308,1.057073,1.128092,0.389675,1.450109,0.063593,1.017430,0.708406,1.741480,0.610699
112323,2,2,2018-07-08,0.610699,0.560488,0.570811,0.433100,0.941031,0.888477,0.539345,0.311186,0.926645,0.086799
112324,2,2,2018-07-09,0.086799,-0.156699,-0.185492,0.020303,-0.670372,-0.533840,-0.117224,-0.060415,-0.514772,0.337736

In [97]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=three_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5759573827425137
MAE: 0.9997676154662491
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.579813847220417
MAE: 2.2268854917188925
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.337851900922219
MAE: 5.3086458687488
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.536861314474677
MAE: 9.34335377605413
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.629073992102295
MAE: 2.6437329033334773
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0716861639465798
MAE: 0.8357961484610211
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.283027104595729
MAE: 0.9259225228307828
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.031564699489393
MAE: 2.1723915267288394
Summary of Performance Statistics
RMSE: 4.755729550686728 +/- 3.9240655077278
MAE: 3.0570619816677738 +/- 2.7371976470932537

## + 12 Neighbors

In [98]:
twelve_neighbors_df = exp_1_df[['row', 'col', 'date', 'delta_pm25_t', 
                                'delta_pm25_t_r1_c0', 'delta_pm25_t_r-1_c0',
                                'delta_pm25_t_r0_c1', 'delta_pm25_t_r0_c-1',
                                'delta_pm25_t_r1_c1', 'delta_pm25_t_r1_c-1',
                                'delta_pm25_t_r-1_c1', 'delta_pm25_t_r-1_c-1',
                                'delta_pm25_t_r-2_c0', 'delta_pm25_t_r2_c0',
                                'delta_pm25_t_r0_c-2', 'delta_pm25_t_r0_c2',
                                'delta_pm25_t+1']]
twelve_neighbors_df.head()

,row,col,date,delta_pm25_t,delta_pm25_t_r1_c0,delta_pm25_t_r-1_c0,delta_pm25_t_r0_c1,delta_pm25_t_r0_c-1,delta_pm25_t_r1_c1,delta_pm25_t_r1_c-1,delta_pm25_t_r-1_c1,delta_pm25_t_r-1_c-1,delta_pm25_t_r-2_c0,delta_pm25_t_r2_c0,delta_pm25_t_r0_c-2,delta_pm25_t_r0_c2,delta_pm25_t+1
112320,2,2,2018-07-05,0.774012,0.198054,1.175132,0.815492,1.526387,0.119964,-0.102599,0.420908,1.152598,0.973524,0.745076,0.531390,-0.076599,-1.214631
112321,2,2,2018-07-06,-1.214631,-0.564943,-1.652848,-0.376699,-2.001883,0.452158,-0.351426,-0.559418,-1.761432,-1.125940,-0.788587,-0.279049,0.366528,1.127308
112322,2,2,2018-07-07,1.127308,1.057073,1.128092,0.389675,1.450109,0.063593,1.017430,0.708406,1.741480,0.587489,0.626072,0.490491,-0.134154,0.610699
112323,2,2,2018-07-08,0.610699,0.560488,0.570811,0.433100,0.941031,0.888477,0.539345,0.311186,0.926645,0.058055,1.012921,1.268657,0.875981,0.086799
112324,2,2,2018-07-09,0.086799,-0.156699,-0.185492,0.020303,-0.670372,-0.533840,-0.117224,-0.060415,-0.514772,0.625493,-0.704665,-1.068175,-0.195938,0.337736

In [99]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=twelve_neighbors_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5676567525416538
MAE: 0.9957675864819716
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.55176015529906
MAE: 2.2277422519410846
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.328219481336435
MAE: 5.30266722826136
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.510267663276371
MAE: 9.332887255981692
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.607239146482127
MAE: 2.6302593583345466
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0649742908195405
MAE: 0.8310171363549559
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2787394698082901
MAE: 0.9238036120911153
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.0224727232573616
MAE: 2.167754604039789
Summary of Performance Statistics
RMSE: 4.741416210352606 +/- 3.917793367523266
MAE: 3.051487379185814 +/- 2.735056626501132

## + 5x5

In [101]:
five_df = exp_1_df[['row', 'col', 'date', 'delta_pm25_t',
                    'delta_pm25_t_r-2_c-2', 'delta_pm25_t_r-2_c-1', 'delta_pm25_t_r-2_c0', 'delta_pm25_t_r-2_c1', 'delta_pm25_t_r-2_c2',
                    'delta_pm25_t_r-1_c-2', 'delta_pm25_t_r-1_c-1', 'delta_pm25_t_r-1_c0', 'delta_pm25_t_r-1_c1', 'delta_pm25_t_r-1_c2',
                    'delta_pm25_t_r0_c-2', 'delta_pm25_t_r0_c-1', 'delta_pm25_t_r0_c1', 'delta_pm25_t_r0_c2',
                    'delta_pm25_t_r1_c-2', 'delta_pm25_t_r1_c-1', 'delta_pm25_t_r1_c0', 'delta_pm25_t_r1_c1', 'delta_pm25_t_r1_c2',
                    'delta_pm25_t_r2_c-2', 'delta_pm25_t_r2_c-1', 'delta_pm25_t_r2_c0', 'delta_pm25_t_r2_c1', 'delta_pm25_t_r2_c2',
                    'delta_pm25_t+1'
]]

five_df.head()

,row,col,date,delta_pm25_t,delta_pm25_t_r-2_c-2,delta_pm25_t_r-2_c-1,delta_pm25_t_r-2_c0,delta_pm25_t_r-2_c1,delta_pm25_t_r-2_c2,delta_pm25_t_r-1_c-2,...,delta_pm25_t_r1_c-1,delta_pm25_t_r1_c0,delta_pm25_t_r1_c1,delta_pm25_t_r1_c2,delta_pm25_t_r2_c-2,delta_pm25_t_r2_c-1,delta_pm25_t_r2_c0,delta_pm25_t_r2_c1,delta_pm25_t_r2_c2,delta_pm25_t+1
112320,2,2,2018-07-05,0.774012,0.302968,0.522349,0.973524,-0.419762,0.275500,0.412996,...,-0.102599,0.198054,0.119964,0.473723,0.354453,0.733201,0.745076,0.145992,0.144983,-1.214631
112321,2,2,2018-07-06,-1.214631,0.601407,-1.001619,-1.125940,-0.095932,-0.186723,0.167479,...,-0.351426,-0.564943,0.452158,0.313466,-0.011651,-0.960510,-0.788587,0.048550,0.975503,1.127308
112322,2,2,2018-07-07,1.127308,0.038002,1.064866,0.587489,0.669046,0.311488,0.411181,...,1.017430,1.057073,0.063593,-0.459555,0.387937,1.195193,0.626072,0.028603,-0.755823,0.610699
112323,2,2,2018-07-08,0.610699,0.556278,0.060918,0.058055,0.167542,0.208978,1.613415,...,0.539345,0.560488,0.888477,1.368596,0.601076,0.385827,1.012921,0.865992,1.554551,0.086799
112324,2,2,2018-07-09,0.086799,-0.491020,0.339427,0.625493,0.176971,0.251034,-1.492460,...,-0.117224,-0.156699,-0.533840,-0.700388,-0.497408,-0.014912,-0.704665,-0.464011,-1.017161,0.337736

In [102]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=five_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5598022066688282
MAE: 0.9893444888842248
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.5091415909438455
MAE: 2.2271945979154117
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.319231141730841
MAE: 5.293315727230608
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 13.49614243020087
MAE: 9.32217443028623
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.572752406523888
MAE: 2.6124138074858134
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0590410167322535
MAE: 0.8264982256104146
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.272808640463271
MAE: 0.9195810767088981
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.0137217655855286
MAE: 2.1604795647993646
Summary of Performance Statistics
RMSE: 4.725330149856166 +/- 3.914793448515558
MAE: 3.0438752398651205 +/- 2.7331534102027497

## Control 2: Exo + Current Pixel Only

In [110]:
control_2_df = train_df[['row', 'col', 'date', 'pm25_t', 'u_wind_10m', 'v_wind_10m',
                        'dew_temp_2m', 'temp_2m', 'surf_pressure', 'precip_sum', 'frp',
                        'elevation', 'delta_pm25_t+1']]

control_2_df.head()

,row,col,date,pm25_t,u_wind_10m,v_wind_10m,dew_temp_2m,temp_2m,surf_pressure,precip_sum,frp,elevation,delta_pm25_t+1
0,0,0,2018-07-05,8.317946,1.432791,0.080936,291.41534,295.22916,85304.766,0.003423,0.0,1360.0,0.601407
1,0,0,2018-07-06,8.919353,0.748148,0.110430,291.74884,295.01360,85287.414,0.007418,0.0,1360.0,0.038002
2,0,0,2018-07-07,8.957355,0.922457,0.196369,292.11148,294.27896,85314.555,0.013237,0.0,1360.0,0.556278
3,0,0,2018-07-08,9.513633,1.040234,0.047216,291.94238,293.10020,85344.050,0.011159,0.0,1360.0,-0.491020
4,0,0,2018-07-09,9.022613,1.154719,0.083273,290.86307,293.92580,85426.945,0.001921,0.0,1360.0,1.041161

In [111]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=control_2_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.6247664205195806
MAE: 0.9944899016250245
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 4.900930010792188
MAE: 2.294106657863162
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 6.988699657193306
MAE: 5.097970069094706
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 12.957978759707443
MAE: 9.163356840585989
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.129106259624338
MAE: 2.340181888558889
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0145065325252662
MAE: 0.7834504441368625
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.3507151692618595
MAE: 0.9892809559238133
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.103746329114961
MAE: 2.2254002906971198
Summary of Performance Statistics
RMSE: 4.508806142342368 +/- 3.713352081431858
MAE: 2.9860296310606955 +/- 2.6668963330140807

## Exo + 4 Dir

In [112]:
four_neighbors_exo_df = exp_1_df[['row', 'col', 'date', 'pm25_t', 'u_wind_10m', 'v_wind_10m',
                                    'dew_temp_2m', 'temp_2m', 'surf_pressure', 'precip_sum', 'frp',
                                    'elevation', 'delta_pm25_t', 
                                    'delta_pm25_t_r1_c0', 'delta_pm25_t_r-1_c0',
                                    'delta_pm25_t_r0_c1', 'delta_pm25_t_r0_c-1',
                                    'delta_pm25_t+1']]
four_neighbors_exo_df.head()

,row,col,date,pm25_t,u_wind_10m,v_wind_10m,dew_temp_2m,temp_2m,surf_pressure,precip_sum,frp,elevation,delta_pm25_t,delta_pm25_t_r1_c0,delta_pm25_t_r-1_c0,delta_pm25_t_r0_c1,delta_pm25_t_r0_c-1,delta_pm25_t+1
112320,2,2,2018-07-05,8.506299,1.099417,0.845259,292.53455,297.36017,88500.48,0.001086,0.0,1018.0,0.774012,0.198054,1.175132,0.815492,1.526387,-1.214631
112321,2,2,2018-07-06,7.291668,0.536112,0.847002,292.94757,296.90536,88492.29,0.002184,0.0,1018.0,-1.214631,-0.564943,-1.652848,-0.376699,-2.001883,1.127308
112322,2,2,2018-07-07,8.418976,0.653129,0.892963,293.46637,296.09024,88523.93,0.010981,0.0,1018.0,1.127308,1.057073,1.128092,0.389675,1.450109,0.610699
112323,2,2,2018-07-08,9.029675,0.758944,0.372737,293.11792,295.39346,88557.59,0.007404,0.0,1018.0,0.610699,0.560488,0.570811,0.433100,0.941031,0.086799
112324,2,2,2018-07-09,9.116474,0.735163,0.694967,292.74075,295.87690,88641.15,0.001646,0.0,1018.0,0.086799,-0.156699,-0.185492,0.020303,-0.670372,0.337736

In [113]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=four_neighbors_exo_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5564052256111849
MAE: 0.994689609480535
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.08042626188442
MAE: 2.3219789122029324
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.057507430296393
MAE: 5.183134363089853
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 12.824998099169092
MAE: 9.165941950010705
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.068097412530483
MAE: 2.3618302486838076
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 1.0000673962786788
MAE: 0.7733748642687686
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.3120897113190704
MAE: 0.9622655549339457
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.028332170653372
MAE: 2.1751877052403383
Summary of Performance Statistics
RMSE: 4.490990463467837 +/- 3.7015550677850624
MAE: 2.992300400988861 +/- 2.680093771265042

## 3x3 + Exo

In [114]:
three_exo_df = exp_1_df[['row', 'col', 'date', 'pm25_t', 'u_wind_10m', 'v_wind_10m',
                        'dew_temp_2m', 'temp_2m', 'surf_pressure', 'precip_sum', 'frp',
                        'elevation', 'delta_pm25_t',  
                        'delta_pm25_t_r1_c0', 'delta_pm25_t_r-1_c0',
                        'delta_pm25_t_r0_c1', 'delta_pm25_t_r0_c-1',
                        'delta_pm25_t_r1_c1', 'delta_pm25_t_r1_c-1',
                        'delta_pm25_t_r-1_c1', 'delta_pm25_t_r-1_c-1',
                        'delta_pm25_t+1']]

three_exo_df.head()

,row,col,date,pm25_t,u_wind_10m,v_wind_10m,dew_temp_2m,temp_2m,surf_pressure,precip_sum,...,delta_pm25_t,delta_pm25_t_r1_c0,delta_pm25_t_r-1_c0,delta_pm25_t_r0_c1,delta_pm25_t_r0_c-1,delta_pm25_t_r1_c1,delta_pm25_t_r1_c-1,delta_pm25_t_r-1_c1,delta_pm25_t_r-1_c-1,delta_pm25_t+1
112320,2,2,2018-07-05,8.506299,1.099417,0.845259,292.53455,297.36017,88500.48,0.001086,...,0.774012,0.198054,1.175132,0.815492,1.526387,0.119964,-0.102599,0.420908,1.152598,-1.214631
112321,2,2,2018-07-06,7.291668,0.536112,0.847002,292.94757,296.90536,88492.29,0.002184,...,-1.214631,-0.564943,-1.652848,-0.376699,-2.001883,0.452158,-0.351426,-0.559418,-1.761432,1.127308
112322,2,2,2018-07-07,8.418976,0.653129,0.892963,293.46637,296.09024,88523.93,0.010981,...,1.127308,1.057073,1.128092,0.389675,1.450109,0.063593,1.017430,0.708406,1.741480,0.610699
112323,2,2,2018-07-08,9.029675,0.758944,0.372737,293.11792,295.39346,88557.59,0.007404,...,0.610699,0.560488,0.570811,0.433100,0.941031,0.888477,0.539345,0.311186,0.926645,0.086799
112324,2,2,2018-07-09,9.116474,0.735163,0.694967,292.74075,295.87690,88641.15,0.001646,...,0.086799,-0.156699,-0.185492,0.020303,-0.670372,-0.533840,-0.117224,-0.060415,-0.514772,0.337736

In [115]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=three_exo_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5536426248101705
MAE: 0.9872114042222759
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.130774402256042
MAE: 2.3249963269864984
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.061683453263363
MAE: 5.158533375982518
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 12.791956261369904
MAE: 9.155188886462732
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.04122790914381
MAE: 2.352153024447235
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 0.9971107695380308
MAE: 0.771534574960101
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.3227786772220909
MAE: 0.9607922564232872
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.0039419373506275
MAE: 2.1610716815395583
Summary of Performance Statistics
RMSE: 4.487889504369255 +/- 3.6947617552455982
MAE: 2.983935191378026 +/- 2.676248134699026

## 12 Neighbors + Exo

In [116]:
twelve_neighbors_exo_df = exp_1_df[['row', 'col', 'date', 'pm25_t', 'u_wind_10m', 'v_wind_10m',
                                    'dew_temp_2m', 'temp_2m', 'surf_pressure', 'precip_sum', 'frp',
                                    'elevation', 'delta_pm25_t',  
                                    'delta_pm25_t_r1_c0', 'delta_pm25_t_r-1_c0',
                                    'delta_pm25_t_r0_c1', 'delta_pm25_t_r0_c-1',
                                    'delta_pm25_t_r1_c1', 'delta_pm25_t_r1_c-1',
                                    'delta_pm25_t_r-1_c1', 'delta_pm25_t_r-1_c-1',
                                    'delta_pm25_t_r-2_c0', 'delta_pm25_t_r2_c0',
                                    'delta_pm25_t_r0_c-2', 'delta_pm25_t_r0_c2',
                                    'delta_pm25_t+1']]
twelve_neighbors_exo_df.head()

,row,col,date,pm25_t,u_wind_10m,v_wind_10m,dew_temp_2m,temp_2m,surf_pressure,precip_sum,...,delta_pm25_t_r0_c-1,delta_pm25_t_r1_c1,delta_pm25_t_r1_c-1,delta_pm25_t_r-1_c1,delta_pm25_t_r-1_c-1,delta_pm25_t_r-2_c0,delta_pm25_t_r2_c0,delta_pm25_t_r0_c-2,delta_pm25_t_r0_c2,delta_pm25_t+1
112320,2,2,2018-07-05,8.506299,1.099417,0.845259,292.53455,297.36017,88500.48,0.001086,...,1.526387,0.119964,-0.102599,0.420908,1.152598,0.973524,0.745076,0.531390,-0.076599,-1.214631
112321,2,2,2018-07-06,7.291668,0.536112,0.847002,292.94757,296.90536,88492.29,0.002184,...,-2.001883,0.452158,-0.351426,-0.559418,-1.761432,-1.125940,-0.788587,-0.279049,0.366528,1.127308
112322,2,2,2018-07-07,8.418976,0.653129,0.892963,293.46637,296.09024,88523.93,0.010981,...,1.450109,0.063593,1.017430,0.708406,1.741480,0.587489,0.626072,0.490491,-0.134154,0.610699
112323,2,2,2018-07-08,9.029675,0.758944,0.372737,293.11792,295.39346,88557.59,0.007404,...,0.941031,0.888477,0.539345,0.311186,0.926645,0.058055,1.012921,1.268657,0.875981,0.086799
112324,2,2,2018-07-09,9.116474,0.735163,0.694967,292.74075,295.87690,88641.15,0.001646,...,-0.670372,-0.533840,-0.117224,-0.060415,-0.514772,0.625493,-0.704665,-1.068175,-0.195938,0.337736

In [117]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=twelve_neighbors_exo_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5404586950514998
MAE: 0.9822771582189067
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.249185006264551
MAE: 2.3656162938731784
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.054573179260198
MAE: 5.17452007426294
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 12.830661413282938
MAE: 9.15042550298882
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.041923543753887
MAE: 2.348736256764067
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 0.9946205788535153
MAE: 0.7704724077944024
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.3482607908673883
MAE: 0.9630094326341432
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 3.0127631134837145
MAE: 2.159457381275197
Summary of Performance Statistics
RMSE: 4.509055790102211 +/- 3.7062130788473375
MAE: 2.9893143134764566 +/- 2.6758126409548537

## 5x5 + Exo

In [119]:
five_exo_df = exp_1_df[['row', 'col', 'date', 'pm25_t', 'u_wind_10m', 'v_wind_10m',
                        'dew_temp_2m', 'temp_2m', 'surf_pressure', 'precip_sum', 'frp',
                        'elevation', 'delta_pm25_t',  
                        'delta_pm25_t_r-2_c-2', 'delta_pm25_t_r-2_c-1', 'delta_pm25_t_r-2_c0', 'delta_pm25_t_r-2_c1', 'delta_pm25_t_r-2_c2',
                        'delta_pm25_t_r-1_c-2', 'delta_pm25_t_r-1_c-1', 'delta_pm25_t_r-1_c0', 'delta_pm25_t_r-1_c1', 'delta_pm25_t_r-1_c2',
                        'delta_pm25_t_r0_c-2', 'delta_pm25_t_r0_c-1', 'delta_pm25_t_r0_c1', 'delta_pm25_t_r0_c2',
                        'delta_pm25_t_r1_c-2', 'delta_pm25_t_r1_c-1', 'delta_pm25_t_r1_c0', 'delta_pm25_t_r1_c1', 'delta_pm25_t_r1_c2',
                        'delta_pm25_t_r2_c-2', 'delta_pm25_t_r2_c-1', 'delta_pm25_t_r2_c0', 'delta_pm25_t_r2_c1', 'delta_pm25_t_r2_c2',
                        'delta_pm25_t+1'
]]

five_exo_df.head()

,row,col,date,pm25_t,u_wind_10m,v_wind_10m,dew_temp_2m,temp_2m,surf_pressure,precip_sum,...,delta_pm25_t_r1_c-1,delta_pm25_t_r1_c0,delta_pm25_t_r1_c1,delta_pm25_t_r1_c2,delta_pm25_t_r2_c-2,delta_pm25_t_r2_c-1,delta_pm25_t_r2_c0,delta_pm25_t_r2_c1,delta_pm25_t_r2_c2,delta_pm25_t+1
112320,2,2,2018-07-05,8.506299,1.099417,0.845259,292.53455,297.36017,88500.48,0.001086,...,-0.102599,0.198054,0.119964,0.473723,0.354453,0.733201,0.745076,0.145992,0.144983,-1.214631
112321,2,2,2018-07-06,7.291668,0.536112,0.847002,292.94757,296.90536,88492.29,0.002184,...,-0.351426,-0.564943,0.452158,0.313466,-0.011651,-0.960510,-0.788587,0.048550,0.975503,1.127308
112322,2,2,2018-07-07,8.418976,0.653129,0.892963,293.46637,296.09024,88523.93,0.010981,...,1.017430,1.057073,0.063593,-0.459555,0.387937,1.195193,0.626072,0.028603,-0.755823,0.610699
112323,2,2,2018-07-08,9.029675,0.758944,0.372737,293.11792,295.39346,88557.59,0.007404,...,0.539345,0.560488,0.888477,1.368596,0.601076,0.385827,1.012921,0.865992,1.554551,0.086799
112324,2,2,2018-07-09,9.116474,0.735163,0.694967,292.74075,295.87690,88641.15,0.001646,...,-0.117224,-0.156699,-0.533840,-0.700388,-0.497408,-0.014912,-0.704665,-0.464011,-1.017161,0.337736

In [120]:
model = xgb.XGBRegressor(
        objective='reg:squarederror',
        **params,
        random_state=191
    )

rmse_scores, mae_scores = T.rolling_window_cv(
    train_days=365 * 2,
    gap_days=21,
    test_days=60,
    df=five_exo_df,
    model=model
)

mean_rmse = np.mean(rmse_scores)
se_rmse = np.std(rmse_scores)

mean_mae = np.mean(mae_scores)
se_mae = np.std(mae_scores)

print("Summary of Performance Statistics")
print(f"RMSE: {mean_rmse} +/- {se_rmse}")
print(f"MAE: {mean_mae} +/- {se_mae}")

Fold 1
2018-07-05 00:00:00 2020-07-19 00:00:00
2020-08-10 00:00:00 2020-10-08 00:00:00
RMSE: 1.5355051141476084
MAE: 0.9778407375318633
Fold 2
2018-09-03 00:00:00 2020-09-17 00:00:00
2020-10-09 00:00:00 2020-12-07 00:00:00
RMSE: 5.277962572744154
MAE: 2.35861406371097
Fold 3
2018-11-02 00:00:00 2020-11-16 00:00:00
2020-12-08 00:00:00 2021-02-05 00:00:00
RMSE: 7.072864608278142
MAE: 5.173320041267818
Fold 4
2019-01-01 00:00:00 2021-01-15 00:00:00
2021-02-06 00:00:00 2021-04-18 00:00:00
RMSE: 12.793278681992668
MAE: 9.110088867753948
Fold 5
2019-03-04 00:00:00 2021-03-28 00:00:00
2021-04-19 00:00:00 2021-06-17 00:00:00
RMSE: 4.015516507489309
MAE: 2.3350350208749475
Fold 6
2019-05-03 00:00:00 2021-05-27 00:00:00
2021-06-18 00:00:00 2021-08-16 00:00:00
RMSE: 0.9848992041582701
MAE: 0.763735042721831
Fold 7
2019-07-02 00:00:00 2021-07-26 00:00:00
2021-08-17 00:00:00 2021-10-15 00:00:00
RMSE: 1.2872082807385457
MAE: 0.9477887194616236
Fold 8
2019-08-31 00:00:00 2021-09-24 00:00:00
2021-10-16 00:00:00 2021-12-14 00:00:00
RMSE: 2.9753117964289704
MAE: 2.1386299660475743
Summary of Performance Statistics
RMSE: 4.492818345747208 +/- 3.7085797362704036
MAE: 2.975631557421322 +/- 2.6680715944691613